#!/usr/bin/perl
use strict;
use warnings;

use File::Find;
use Data::Printer;

my $RT_lib_dir = "/home/bruno/dev/ee/rt/bin2/lib/";

# This scripts auto-generates list of parameters for Request Tracker modules (defined in  _OverlayAccessible, _VendorAccessible and _LocalAccessible functions)
# and outputs it to STROUT. It's used to generate attributes_list.md file

print <<EOL;
# Request Tracker accessible parameters list
This is an autogenerated file by `list_attributes.pl` script.

EOL


find({wanted => \&analyse_file, no_chdir => 1}, $RT_lib_dir);

my %result;

sub analyse_file {
    my $filename = $_;
    return if (! $filename =~ /.*\.pm$/);
    my $packageName = undef;
    my $isInstance = 0;
    open my $file, '<:encoding(UTF-8)', $filename or die;
    while (my $line = <$file>) {
        if ($line =~ /package ((\w|:)+);/) {
            $packageName = $1;
        }
        if ($line =~ /use base 'RT::Record'/) {
            $isInstance = 1;
        }
    }
    if ($isInstance) {
        seek $file, 0, 0;  # Rewind file
        my @params = ();
        # Find for _OverlayAccessible _VendorAccessible or _LocalAccessible function
        while (my $line = <$file>) {
            if ($line =~ /sub _\w+Accessible/) {
                # Beginning of block
                while (my $line = <$file>) {
                    if ($line =~ /^\s*\};$/) {  # Fin for "};"
                        # End of block
                        last;
                    }
                    if ($line =~ /^\s*(\w+)\s*=>/) {  # };
                        # This is a param. Add it to param list if it's not already in list
                        my $param = $1;
                        if (! grep {$_ eq $param} @params) {
                            push @params, $param
                        }
                    }
                }
            }
        }
        if (@params) {
            # Add this params to result hash
            $result{$packageName} = [@params];
        }
    }
}

# Finaly print results
foreach my $packageName (sort keys %result) {
    print "\n## $packageName\n";
    my $params = $result{$packageName};
    foreach (sort @{$params}) {
        print "  - $_\n";
    }
}
